name:                language-lyapas
version:             0.1.0
license:             GPL-3
author:              "d86leader"
maintainer:          "d86leader@mail.com"

category: Language
synopsis: "Analysis and generation of lyapas code"
description:
  " A haskell library for analysis and generation of lyapas code.
  It features a parser for a most common subset of vЛЯПАС
  and an interpreter for the intermediate representation.
  Soon to have a compiler too!
  "

ghc-options:
- -Wall -Wcompat
default-extensions: OverloadedStrings LambdaCase BangPatterns NamedFieldPuns

library:
  source-dirs:         src
  dependencies:
  - base
  - bytestring
  - data-default-class
  - clock
  - containers
  - exceptions
  - hashable
  - megaparsec >= 9.0.0
  - mono-traversable
  - mtl
  - optics-core
  - optics-extra
  - optics-th
  - parser-combinators
  - random
  - text
  - transformers
  - unordered-containers
  - vector

executables:
  nlyapas:
    main: Main.hs
    source-dirs: nlyapas
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - exceptions
    - directory
    - haskeline
    - language-lyapas
    - megaparsec >= 9.0.0
    - mtl
    - process
    - text
